CREATE TABLE "GCG_6625_ORD_EXCLS"(
 "ORDER_TYPE" CHAR(1),
 "ITEM_CATEGORY" CHAR(4),
 "PLANT" CHAR(4),
 "VALID_START_DATE" DATE,
 "VALID_END_DATE" DATE,
 "DESCRIPTION" VARCHAR(120),
 "LAST_MODIFIED_USER" CHAR(12),
 "LAST_MODIFIED" DATETIME );