CREATE TABLE "GCG_6625_PARTNER"(
 "CO_CODE" CHAR(4),
 "PARTNER_ID" CHAR(14),
 "PARTNER_TYPE" CHAR(1),
 "DECISION" CHAR(1),
 "CRIMEA_HOLD" BIT NOT NULL,
 "DATE_TIME" DATETIME,
 "END_USER_DESIG" CHAR(25) );