CREATE TABLE "GCG_6625_ORD_DELIV" (
 "TRANS_ID" CHAR(7),
 "TRANS_TYPE" CHAR(1),
 "PASS_FAIL_DPL" CHAR(1),
 "PASS_FAIL_LIC" CHAR(1),
 "PASS_FAIL_DATA" CHAR(1),
 "POSNR" CHAR(4),
 "PARTID" VARCHAR(50),
 "STATUS3" CHAR(1),
 "LIC_NUM" VARCHAR(25),
 "EXP_DAT" DATE,
 "PASS_FAIL_EUC" CHAR(1),
 "PACKING_LIST" CHAR(7) );