CREATE TABLE "GCG_6625_DELIV_EXCLS" (
 "LOCATION" CHAR(4),
 "DELIVERY_TYPE" CHAR(4),
 "VALID_START_DATE" DATE,
 "VALID_END_DATE" DATE,
 "DESCRIPTION" VARCHAR(120),
 "LAST_MODIFIED_USER" CHAR(12),
 "LAST_MODIFIED_DATETIME" DATETIME );